import { db } from '@/db';
import { bookings } from '@/db/schema';

async function main() {
    const sampleBookings = [
        {
            farmerId: 4,
            resourceId: 1,
            ownerId: 4,
            startDate: new Date('2024-01-15').toISOString(),
            endDate: new Date('2024-01-20').toISOString(),
            totalPrice: 2500.00,
            status: 'completed',
            cropType: 'Wheat',
            farmStage: 'Land Preparation',
            cropWeight: '1000 kg',
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            farmerId: 5,
            resourceId: 3,
            ownerId: 6,
            startDate: new Date('2024-02-01').toISOString(),
            endDate: new Date('2024-02-05').toISOString(),
            totalPrice: 2000.00,
            status: 'confirmed',
            cropType: 'Rice',
            farmStage: 'Sowing',
            cropWeight: '500 kg',
            createdAt: new Date('2024-01-28').toISOString(),
        },
        {
            farmerId: 6,
            resourceId: 5,
            ownerId: 8,
            startDate: new Date('2024-02-10').toISOString(),
            endDate: new Date('2024-02-17').toISOString(),
            totalPrice: 4200.00,
            status: 'confirmed',
            cropType: 'Sugarcane',
            farmStage: 'Harvesting',
            cropWeight: '2 tons',
            createdAt: new Date('2024-02-05').toISOString(),
        },
        {
            farmerId: 7,
            resourceId: 8,
            ownerId: 6,
            startDate: new Date('2024-02-20').toISOString(),
            endDate: new Date('2024-02-24').toISOString(),
            totalPrice: 2000.00,
            status: 'pending',
            cropType: 'Cotton',
            farmStage: 'Land Preparation',
            cropWeight: '1.5 tons',
            createdAt: new Date('2024-02-18').toISOString(),
        },
        {
            farmerId: 8,
            resourceId: 10,
            ownerId: 8,
            startDate: new Date('2024-03-01').toISOString(),
            endDate: new Date('2024-03-06').toISOString(),
            totalPrice: 3000.00,
            status: 'confirmed',
            cropType: 'Maize',
            farmStage: 'Sowing',
            cropWeight: '1000 kg',
            createdAt: new Date('2024-02-25').toISOString(),
        },
        {
            farmerId: 4,
            resourceId: 12,
            ownerId: 5,
            startDate: new Date('2024-03-10').toISOString(),
            endDate: new Date('2024-03-14').toISOString(),
            totalPrice: 2000.00,
            status: 'pending',
            cropType: 'Potato',
            farmStage: 'Harvesting',
            cropWeight: '2 tons',
            createdAt: new Date('2024-03-08').toISOString(),
        },
        {
            farmerId: 5,
            resourceId: 14,
            ownerId: 7,
            startDate: new Date('2024-03-15').toISOString(),
            endDate: new Date('2024-03-21').toISOString(),
            totalPrice: 3600.00,
            status: 'confirmed',
            cropType: 'Wheat',
            farmStage: 'Post-Harvest',
            cropWeight: '1.5 tons',
            createdAt: new Date('2024-03-12').toISOString(),
        },
        {
            farmerId: 6,
            resourceId: 2,
            ownerId: 5,
            startDate: new Date('2024-03-25').toISOString(),
            endDate: new Date('2024-03-29').toISOString(),
            totalPrice: 2400.00,
            status: 'pending',
            cropType: 'Rice',
            farmStage: 'Land Preparation',
            cropWeight: '500 kg',
            createdAt: new Date('2024-03-22').toISOString(),
        },
        {
            farmerId: 7,
            resourceId: 6,
            ownerId: 4,
            startDate: new Date('2024-01-25').toISOString(),
            endDate: new Date('2024-01-30').toISOString(),
            totalPrice: 2500.00,
            status: 'completed',
            cropType: 'Cotton',
            farmStage: 'Sowing',
            cropWeight: '1000 kg',
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            farmerId: 8,
            resourceId: 9,
            ownerId: 7,
            startDate: new Date('2024-02-15').toISOString(),
            endDate: new Date('2024-02-18').toISOString(),
            totalPrice: 1800.00,
            status: 'cancelled',
            cropType: 'Sugarcane',
            farmStage: 'Harvesting',
            cropWeight: '2 tons',
            createdAt: new Date('2024-02-10').toISOString(),
        },
    ];

    await db.insert(bookings).values(sampleBookings);
    
    console.log('✅ Bookings seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});