import { db } from '@/db';
import { resources } from '@/db/schema';

async function main() {
    const sampleResources = [
        {
            ownerId: 4,
            name: 'John Deere 5310 Tractor',
            type: 'tractor',
            description: 'Heavy-duty tractor with 55 HP engine, perfect for plowing, cultivation, and heavy farm work. Equipped with power steering and comfortable seating.',
            pricePerDay: 3500,
            capacity: '55 HP',
            location: 'Ludhiana, Punjab',
            latitude: 30.9010,
            longitude: 75.8573,
            imageUrl: '/images/tractor1.jpg',
            status: 'verified',
            verifiedBy: 1,
            createdAt: new Date('2024-11-15').toISOString(),
        },
        {
            ownerId: 5,
            name: 'Mahindra 575 DI Tractor',
            type: 'tractor',
            description: 'Powerful 47 HP tractor ideal for medium to large farms. Features excellent fuel efficiency and robust build quality for long-lasting performance.',
            pricePerDay: 3200,
            capacity: '47 HP',
            location: 'Amritsar, Punjab',
            latitude: 31.6340,
            longitude: 74.8723,
            imageUrl: '/images/tractor2.jpg',
            status: 'verified',
            verifiedBy: 2,
            createdAt: new Date('2024-11-20').toISOString(),
        },
        {
            ownerId: 6,
            name: 'Sonalika DI 60 Tractor',
            type: 'tractor',
            description: '60 HP tractor with advanced hydraulic system. Suitable for all farming operations including plowing, harrowing, and transportation.',
            pricePerDay: 3800,
            capacity: '60 HP',
            location: 'Jalandhar, Punjab',
            latitude: 31.3260,
            longitude: 75.5762,
            imageUrl: '/images/tractor3.jpg',
            status: 'pending',
            verifiedBy: null,
            createdAt: new Date('2024-12-05').toISOString(),
        },
        {
            ownerId: 7,
            name: 'John Deere 5105 Tractor',
            type: 'tractor',
            description: 'Reliable 40 HP tractor with excellent maneuverability. Perfect for small to medium farms, orchards, and vegetable cultivation.',
            pricePerDay: 2800,
            capacity: '40 HP',
            location: 'Patiala, Punjab',
            latitude: 30.3398,
            longitude: 76.3869,
            imageUrl: '/images/tractor4.jpg',
            status: 'verified',
            verifiedBy: 3,
            createdAt: new Date('2024-11-25').toISOString(),
        },
        {
            ownerId: 8,
            name: 'Mahindra 265 DI Tractor',
            type: 'tractor',
            description: 'Compact 30 HP tractor ideal for small farms and inter-cultivation. Features smooth operation and easy maintenance.',
            pricePerDay: 2200,
            capacity: '30 HP',
            location: 'Bathinda, Punjab',
            latitude: 30.2110,
            longitude: 74.9455,
            imageUrl: '/images/tractor5.jpg',
            status: 'verified',
            verifiedBy: 1,
            createdAt: new Date('2024-12-01').toISOString(),
        },
        {
            ownerId: 4,
            name: 'Kartar 4000 Combine Harvester',
            type: 'harvester',
            description: 'High-capacity combine harvester for wheat and rice. Features advanced threshing mechanism and large grain tank capacity.',
            pricePerDay: 5000,
            capacity: '2500 kg',
            location: 'Ludhiana, Punjab',
            latitude: 30.9100,
            longitude: 75.8500,
            imageUrl: '/images/harvester1.jpg',
            status: 'verified',
            verifiedBy: 2,
            createdAt: new Date('2024-11-10').toISOString(),
        },
        {
            ownerId: 5,
            name: 'Preet 987 Rice Harvester',
            type: 'harvester',
            description: 'Specialized rice harvester with excellent cutting and threshing efficiency. Suitable for paddy fields with muddy conditions.',
            pricePerDay: 4800,
            capacity: '2200 kg',
            location: 'Amritsar, Punjab',
            latitude: 31.6300,
            longitude: 74.8800,
            imageUrl: '/images/harvester2.jpg',
            status: 'verified',
            verifiedBy: 3,
            createdAt: new Date('2024-11-18').toISOString(),
        },
        {
            ownerId: 6,
            name: 'John Deere W70 Harvester',
            type: 'harvester',
            description: 'Multi-crop harvester capable of harvesting wheat, rice, and maize. Features advanced grain cleaning system and comfortable cabin.',
            pricePerDay: 5500,
            capacity: '3000 kg',
            location: 'Jalandhar, Punjab',
            latitude: 31.3200,
            longitude: 75.5800,
            imageUrl: '/images/harvester3.jpg',
            status: 'pending',
            verifiedBy: null,
            createdAt: new Date('2024-12-08').toISOString(),
        },
        {
            ownerId: 7,
            name: 'Mahindra Arjun Ultra Harvester',
            type: 'harvester',
            description: 'Efficient harvester for small to medium farms. Easy to operate with low maintenance requirements and excellent fuel economy.',
            pricePerDay: 4200,
            capacity: '1800 kg',
            location: 'Patiala, Punjab',
            latitude: 30.3450,
            longitude: 76.3900,
            imageUrl: '/images/harvester4.jpg',
            status: 'verified',
            verifiedBy: 1,
            createdAt: new Date('2024-11-22').toISOString(),
        },
        {
            ownerId: 8,
            name: 'Fieldking 8-Row Seed Planter',
            type: 'planter',
            description: 'Precision seed planter for wheat, corn, and soybean. Features accurate seed placement and adjustable row spacing.',
            pricePerDay: 2500,
            capacity: '8 rows',
            location: 'Ludhiana, Punjab',
            latitude: 30.9050,
            longitude: 75.8600,
            imageUrl: '/images/planter1.jpg',
            status: 'verified',
            verifiedBy: 2,
            createdAt: new Date('2024-11-28').toISOString(),
        },
        {
            ownerId: 4,
            name: 'Mahindra 6-Row Multi-Crop Planter',
            type: 'planter',
            description: 'Versatile planter suitable for various crops including cotton, sunflower, and vegetables. Features adjustable seed rate control.',
            pricePerDay: 2200,
            capacity: '6 rows',
            location: 'Amritsar, Punjab',
            latitude: 31.6400,
            longitude: 74.8650,
            imageUrl: '/images/planter2.jpg',
            status: 'pending',
            verifiedBy: null,
            createdAt: new Date('2024-12-10').toISOString(),
        },
        {
            ownerId: 5,
            name: 'John Deere 1770NT Planter',
            type: 'planter',
            description: 'High-precision 12-row planter with vacuum metering system. Ideal for large-scale farming operations and ensures uniform seed placement.',
            pricePerDay: 3200,
            capacity: '12 rows',
            location: 'Jalandhar, Punjab',
            latitude: 31.3300,
            longitude: 75.5700,
            imageUrl: '/images/planter3.jpg',
            status: 'verified',
            verifiedBy: 3,
            createdAt: new Date('2024-11-12').toISOString(),
        },
        {
            ownerId: 6,
            name: 'Neptune 500L Tractor-Mounted Sprayer',
            type: 'sprayer',
            description: 'High-capacity boom sprayer with 12-meter spray width. Perfect for pesticide and fertilizer application on large fields.',
            pricePerDay: 1800,
            capacity: '500 liters',
            location: 'Patiala, Punjab',
            latitude: 30.3350,
            longitude: 76.3950,
            imageUrl: '/images/sprayer1.jpg',
            status: 'verified',
            verifiedBy: 1,
            createdAt: new Date('2024-11-30').toISOString(),
        },
        {
            ownerId: 7,
            name: 'Kisankraft 800L Boom Sprayer',
            type: 'sprayer',
            description: 'Heavy-duty sprayer with adjustable nozzles and pressure control. Suitable for both pesticide and liquid fertilizer application.',
            pricePerDay: 2100,
            capacity: '800 liters',
            location: 'Bathinda, Punjab',
            latitude: 30.2150,
            longitude: 74.9500,
            imageUrl: '/images/sprayer2.jpg',
            status: 'pending',
            verifiedBy: null,
            createdAt: new Date('2024-12-03').toISOString(),
        },
        {
            ownerId: 8,
            name: 'Honda WJR3625 Power Sprayer',
            type: 'sprayer',
            description: 'Portable power sprayer with 25-liter capacity. Ideal for small farms, orchards, and vegetable gardens. Easy to operate and maintain.',
            pricePerDay: 800,
            capacity: '25 liters',
            location: 'Ludhiana, Punjab',
            latitude: 30.9150,
            longitude: 75.8450,
            imageUrl: '/images/sprayer3.jpg',
            status: 'verified',
            verifiedBy: 2,
            createdAt: new Date('2024-12-07').toISOString(),
        },
    ];

    await db.insert(resources).values(sampleResources);
    
    console.log('✅ Resources seeder completed successfully - 15 agricultural equipment records created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});